# Container test/playtest harness (#1123). These targets are the safe way
# to run the full suite or a TUI play-test on a shared dev box: everything
# runs inside docker/podman with no access to the host tmux server, the
# real ~/.agent-factory, or this repo's worktrees.
# See docs/container-testing.md.

.PHONY: test-container playtest-container playtest-container-detached \
	tui-driver tui-driver-selftest testbox-image lint-file-length docs

# Structural-health lint (#1145): fail if any Go file exceeds its line limit
# (1000 for production code, 1500 for *_test.go) unless grandfathered in
# scripts/file-length-allowlist.txt. Runs on the host — no container needed.
# See docs/file-length-lint.md.
lint-file-length:
	scripts/lint-file-length.sh

# Regenerate the autogenerated docs reference pages (docs/reference/{cli,api}.md)
# from the Cobra command tree and the daemon HTTP route catalog. CI fails if the
# committed output is stale (.github/workflows/docs.yml). Run and commit the
# result whenever a command, flag, or HTTP route changes.
docs:
	scripts/gen-docs.sh

# Full `go test ./...` inside the container — the one sanctioned way to run
# the bare full suite on a shared box. Narrow or extend the run with
# GOTESTARGS, e.g.: make test-container GOTESTARGS="-race ./daemon/..."
test-container:
	scripts/testbox.sh test $(GOTESTARGS)

# Interactive TUI play-test sandbox: builds af inside, scaffolds a
# throwaway AF home + mock project repo, drops you in a shell with a
# private tmux server. Exiting the shell tears everything down.
playtest-container:
	scripts/testbox.sh playtest

# Same sandbox parked in the background for `docker exec` driving (used by
# the tui-playtest skill). The container name is unique per run (#1171) and
# printed on start; pin it with AF_PLAYTEST_NAME to target/tear down a
# specific one (docker rm -f "$AF_PLAYTEST_NAME").
playtest-container-detached:
	scripts/testbox.sh playtest -d

# Deterministic, scriptable TUI driver (#1161). tui-driver boots af through
# the driver in a uniquely-named container sandbox (#1171) and attaches you to
# the live session to drive it by hand (it prints its teardown command);
# tui-driver-selftest runs the acceptance scenario (boot → 2 instances →
# select → pane → interactive → type → attach/detach → assert selection + no
# orphan clients) in an EPHEMERAL sandbox that is torn down automatically.
# See docs/tui-manual-testing.md.
tui-driver:
	scripts/testbox.sh drive

tui-driver-selftest:
	scripts/testbox.sh selftest

# (Re)build the toolchain image only.
testbox-image:
	scripts/testbox.sh build
