# Container test/playtest harness (#1123). These targets are the safe way
# to run the full suite or a TUI play-test on a shared dev box: everything
# runs inside docker/podman with no access to the host tmux server, the
# real ~/.agent-factory, or this repo's worktrees.
# See docs/container-testing.md.

.PHONY: test-container remote-roundtrip-container ws-pty-roundtrip-container \
	agent-server-roundtrip-container remote-agent-server-roundtrip-container \
	backend-docker-roundtrip backend-ssh-roundtrip \
	playtest-container playtest-container-detached tui-driver tui-driver-selftest \
	lifecycle-container \
	testbox-image lint-file-length docs web-build web-test web-selftest-container

# Structural-health lint (#1145): fail if any Go file exceeds its line limit
# (1000 for production code, 1500 for *_test.go) unless grandfathered in
# scripts/file-length-allowlist.txt. Runs on the host — no container needed.
# See docs/file-length-lint.md.
lint-file-length:
	scripts/lint-file-length.sh

# Regenerate the autogenerated docs reference pages (docs/reference/{cli,api}.md)
# from the Cobra command tree and the daemon HTTP route catalog. CI fails if the
# committed output is stale (.github/workflows/docs.yml). Run and commit the
# result whenever a command, flag, or HTTP route changes.
docs:
	scripts/gen-docs.sh

# Full `go test ./...` inside the container — the one sanctioned way to run
# the bare full suite on a shared box. Narrow or extend the run with
# GOTESTARGS, e.g.: make test-container GOTESTARGS="-race ./daemon/..."
test-container:
	scripts/testbox.sh test $(GOTESTARGS)

# Focused remote-hook integration harness (#1039): runs the mock remote
# round-trip gate inside the same container fence as the full suite.
remote-roundtrip-container:
	scripts/testbox.sh test ./integration -run TestRemoteHookRoundTripMockRemote

# Focused WS PTY broker harness (#1592 Phase 2 PR5): connects two subscribers to
# a real local session's stream, exercises multi-writer input, last-resize-wins +
# echo, ?since replay, and keepalive dead-subscriber drop — inside the same
# container fence (a real tmux server) as the full suite.
ws-pty-roundtrip-container:
	scripts/testbox.sh test ./integration -run TestWSPTYBrokerRoundTrip

# Focused headless agent-server harness (#1592 Phase 4 PR1): starts a REAL
# out-of-process `af agent-server` on a loopback TLS+token listener and drives it
# over HTTPS/WSS — provision/launch, PTY stream input echo, snapshot — inside the
# same container fence (a real tmux server) as the full suite.
agent-server-roundtrip-container:
	scripts/testbox.sh test ./integration -run TestAgentServerRoundTrip

# Focused remote agent-server harness (#1592 Phase 4 PR2 — the de-risk): starts a
# REAL out-of-process `af agent-server` on a loopback TLS+token listener and drives
# it through the daemon-side session.remoteAgentServer HTTP/WS client — the full
# AgentServer surface (provision/launch/subscribe/input/snapshot/preview/kill)
# across the process boundary — inside the same container fence as the full suite.
remote-agent-server-roundtrip-container:
	scripts/testbox.sh test ./integration -run TestRemoteAgentServerRoundTrip

# Flagship docker backend round-trip (#1592 Phase 4 PR4/PR6): runs a session in a
# REAL container to parity — build a slim git+tmux+bash image, create a session
# on backend=docker, drive the in-container `af agent-server` over wss://+token
# (Provision/Launch → PTY input echo → preview/snapshot/alive), then Kill and
# assert the container is reaped. The PR6 archive/restore case additionally
# commits real work on the session branch, ARCHIVES it (branch pushed to origin,
# container reaped), RESTORES it (fresh container clones the branch back, the
# commit is present, the session is drivable again) — proving state survives via
# GitHub. Runs ON THE HOST (needs a real docker daemon); it is NOT inside the
# testbox fence, which has no docker. SKIPS cleanly where docker is unavailable.
# See docs/backends.md.
backend-docker-roundtrip:
	go test ./integration -run 'TestDockerBackend(RoundTrip|ArchiveRestore)' -v -count=1 -timeout 20m

# SSH remote-machine backend round-trip (#1592 Phase 4 PR5/PR6): runs a session on
# a REAL remote host over ssh to parity — stand up a throwaway sshd+git+tmux
# container as the ssh target, create a session on backend=ssh pointing at it, and
# drive the remote `af agent-server` over the ssh-tunneled wss://+token
# (Provision/Launch → PTY input echo → preview/snapshot/alive), then Kill and
# assert the remote agent-server process is reaped + the session dir removed + the
# tunnel closed. The PR6 archive/restore case additionally commits real work,
# ARCHIVES it (branch pushed to origin, remote sandbox reaped), RESTORES it (fresh
# remote clones the branch back, the commit is present, the session is drivable)
# — the identical push/pull-branch flow, over ssh. Uses the Go x/crypto/ssh client
# for a real ssh clone + tunnel with no external host or the box's own sshd. Runs
# ON THE HOST (needs a real docker daemon to host the sshd target); SKIPS cleanly
# where docker is unavailable. See docs/backends.md.
backend-ssh-roundtrip:
	go test ./integration -run 'TestSSHBackend(RoundTrip|ArchiveRestore)' -v -count=1 -timeout 20m

# Interactive TUI play-test sandbox: builds af inside, scaffolds a
# throwaway AF home + mock project repo, drops you in a shell with a
# private tmux server. Exiting the shell tears everything down.
playtest-container:
	scripts/testbox.sh playtest

# Same sandbox parked in the background for `docker exec` driving (used by
# the tui-playtest skill). The container name is unique per run (#1171) and
# printed on start; pin it with AF_PLAYTEST_NAME to target/tear down a
# specific one (docker rm -f "$AF_PLAYTEST_NAME").
playtest-container-detached:
	scripts/testbox.sh playtest -d

# Deterministic, scriptable TUI driver (#1161). tui-driver boots af through
# the driver in a uniquely-named container sandbox (#1171) and attaches you to
# the live session to drive it by hand (it prints its teardown command);
# tui-driver-selftest runs the acceptance scenario (boot → 2 instances →
# select → pane → interactive → type → attach/detach → assert selection + no
# orphan clients) in an EPHEMERAL sandbox that is torn down automatically.
# See docs/tui-manual-testing.md.
tui-driver:
	scripts/testbox.sh drive

tui-driver-selftest:
	scripts/testbox.sh selftest

# Clean-environment install + upgrade gate. Every other target here tests THIS
# TREE in isolation; this one installs a REAL previous release into a throwaway
# machine, puts sessions on it, upgrades it the way a user does, and asserts the
# machine is coherent afterwards (daemon restarted onto the new binary, no
# version skew, one daemon, sessions survived, doctor clean).
#
# That version boundary is where the bugs users actually hit this week live —
# #1921 (new client vs old daemon), #796 (daemon demoted from its unit) — and no
# single-version test can construct it.
#
# Needs network: it downloads published release tarballs. Wired nightly rather
# than per-PR for that reason (.github/workflows/lifecycle.yml). The container
# has no systemd, so the supervision assertion is SKIPped here and covered by
# the CI runner leg. Narrow the run with LIFECYCLE_SCENARIO=scenario-a.
# See docs/lifecycle-testing.md.
lifecycle-container:
	scripts/testbox.sh lifecycle $(LIFECYCLE_SCENARIO)

# (Re)build the toolchain image only.
testbox-image:
	scripts/testbox.sh build

# Web client toolchain (#1592 Phase 5). The JS build+test are gated ENTIRELY behind
# these targets: `go build ./...` and `make test-container` never invoke Node — the
# built web/dist/ is committed so the Go side is self-sufficient. Both targets depend
# on web/node_modules, an order-only-style file target rebuilt from the lockfile.
#
# web/node_modules is a real file target: `npm ci` runs only when the committed
# package-lock.json (or package.json) is newer than the installed tree, so repeated
# web-build/web-test don't reinstall. Deleting web/node_modules forces a fresh `npm ci`.
web/node_modules: web/package-lock.json web/package.json
	cd web && npm ci
	@touch web/node_modules

# esbuild the SPA bundle into the committed web/dist/ (design §3.1, §1.3). PR1 bundles
# only the wire-frame codec; later PRs add the UI and go:embed dist/ into the daemon.
web-build: web/node_modules
	cd web && npm run build

# TypeScript unit tests: the frame golden-vector parity (web/src/frame.test.ts)
# asserting the TS codec is byte-identical to the Go encoder against the SAME fixture
# (agentproto/testdata/frame_vectors.json). Also typechecks the sources. The
# Playwright browser harness lands in PR6 (`make web-selftest-container`); the dep is
# wired now but not invoked here.
web-test: web/node_modules
	cd web && npm run typecheck && npm run test

# Playwright web-driver-selftest (#1592 Phase 5 PR6): the browser analogue of
# tui-driver-selftest. It builds a dedicated Go+Node+Chromium image and runs the
# WHOLE harness inside ONE ephemeral container — build af, boot a real daemon on a
# loopback TLS+token listener, open the embedded SPA in headless Chromium, and
# assert the core flows (login, sidebar, click-to-attach + live xterm output, the
# #1694 j/k/Enter/Esc keyboard model, create/kill/archive). Assertions are the
# gate, not screenshots. Node/Playwright stay behind this target — the Go build and
# `make test-container` never invoke them. Needs a real docker/podman daemon; the
# whole run is fenced in the container, isolated from the host tmux + real AF home.
# See docs/web-selftest.md.
web-selftest-container:
	scripts/testbox.sh web-selftest
