# Container test/playtest harness (#1123). These targets are the safe way
# to run the full suite or a TUI play-test on a shared dev box: everything
# runs inside docker/podman with no access to the host tmux server, the
# real ~/.agent-factory, or this repo's worktrees.
# See docs/container-testing.md.

.PHONY: test-container remote-roundtrip-container ws-pty-roundtrip-container \
	agent-server-roundtrip-container remote-agent-server-roundtrip-container \
	backend-docker-roundtrip backend-ssh-roundtrip \
	playtest-container playtest-container-detached tui-driver tui-driver-selftest \
	testbox-image lint-file-length docs

# Structural-health lint (#1145): fail if any Go file exceeds its line limit
# (1000 for production code, 1500 for *_test.go) unless grandfathered in
# scripts/file-length-allowlist.txt. Runs on the host — no container needed.
# See docs/file-length-lint.md.
lint-file-length:
	scripts/lint-file-length.sh

# Regenerate the autogenerated docs reference pages (docs/reference/{cli,api}.md)
# from the Cobra command tree and the daemon HTTP route catalog. CI fails if the
# committed output is stale (.github/workflows/docs.yml). Run and commit the
# result whenever a command, flag, or HTTP route changes.
docs:
	scripts/gen-docs.sh

# Full `go test ./...` inside the container — the one sanctioned way to run
# the bare full suite on a shared box. Narrow or extend the run with
# GOTESTARGS, e.g.: make test-container GOTESTARGS="-race ./daemon/..."
test-container:
	scripts/testbox.sh test $(GOTESTARGS)

# Focused remote-hook integration harness (#1039): runs the mock remote
# round-trip gate inside the same container fence as the full suite.
remote-roundtrip-container:
	scripts/testbox.sh test ./integration -run TestRemoteHookRoundTripMockRemote

# Focused WS PTY broker harness (#1592 Phase 2 PR5): connects two subscribers to
# a real local session's stream, exercises multi-writer input, last-resize-wins +
# echo, ?since replay, and keepalive dead-subscriber drop — inside the same
# container fence (a real tmux server) as the full suite.
ws-pty-roundtrip-container:
	scripts/testbox.sh test ./integration -run TestWSPTYBrokerRoundTrip

# Focused headless agent-server harness (#1592 Phase 4 PR1): starts a REAL
# out-of-process `af agent-server` on a loopback TLS+token listener and drives it
# over HTTPS/WSS — provision/launch, PTY stream input echo, snapshot — inside the
# same container fence (a real tmux server) as the full suite.
agent-server-roundtrip-container:
	scripts/testbox.sh test ./integration -run TestAgentServerRoundTrip

# Focused remote agent-server harness (#1592 Phase 4 PR2 — the de-risk): starts a
# REAL out-of-process `af agent-server` on a loopback TLS+token listener and drives
# it through the daemon-side session.remoteAgentServer HTTP/WS client — the full
# AgentServer surface (provision/launch/subscribe/input/snapshot/preview/kill)
# across the process boundary — inside the same container fence as the full suite.
remote-agent-server-roundtrip-container:
	scripts/testbox.sh test ./integration -run TestRemoteAgentServerRoundTrip

# Flagship docker backend round-trip (#1592 Phase 4 PR4/PR6): runs a session in a
# REAL container to parity — build a slim git+tmux+bash image, create a session
# on backend=docker, drive the in-container `af agent-server` over wss://+token
# (Provision/Launch → PTY input echo → preview/snapshot/alive), then Kill and
# assert the container is reaped. The PR6 archive/restore case additionally
# commits real work on the session branch, ARCHIVES it (branch pushed to origin,
# container reaped), RESTORES it (fresh container clones the branch back, the
# commit is present, the session is drivable again) — proving state survives via
# GitHub. Runs ON THE HOST (needs a real docker daemon); it is NOT inside the
# testbox fence, which has no docker. SKIPS cleanly where docker is unavailable.
# See docs/backends.md.
backend-docker-roundtrip:
	go test ./integration -run 'TestDockerBackend(RoundTrip|ArchiveRestore)' -v -count=1 -timeout 20m

# SSH remote-machine backend round-trip (#1592 Phase 4 PR5/PR6): runs a session on
# a REAL remote host over ssh to parity — stand up a throwaway sshd+git+tmux
# container as the ssh target, create a session on backend=ssh pointing at it, and
# drive the remote `af agent-server` over the ssh-tunneled wss://+token
# (Provision/Launch → PTY input echo → preview/snapshot/alive), then Kill and
# assert the remote agent-server process is reaped + the session dir removed + the
# tunnel closed. The PR6 archive/restore case additionally commits real work,
# ARCHIVES it (branch pushed to origin, remote sandbox reaped), RESTORES it (fresh
# remote clones the branch back, the commit is present, the session is drivable)
# — the identical push/pull-branch flow, over ssh. Uses the Go x/crypto/ssh client
# for a real ssh clone + tunnel with no external host or the box's own sshd. Runs
# ON THE HOST (needs a real docker daemon to host the sshd target); SKIPS cleanly
# where docker is unavailable. See docs/backends.md.
backend-ssh-roundtrip:
	go test ./integration -run 'TestSSHBackend(RoundTrip|ArchiveRestore)' -v -count=1 -timeout 20m

# Interactive TUI play-test sandbox: builds af inside, scaffolds a
# throwaway AF home + mock project repo, drops you in a shell with a
# private tmux server. Exiting the shell tears everything down.
playtest-container:
	scripts/testbox.sh playtest

# Same sandbox parked in the background for `docker exec` driving (used by
# the tui-playtest skill). The container name is unique per run (#1171) and
# printed on start; pin it with AF_PLAYTEST_NAME to target/tear down a
# specific one (docker rm -f "$AF_PLAYTEST_NAME").
playtest-container-detached:
	scripts/testbox.sh playtest -d

# Deterministic, scriptable TUI driver (#1161). tui-driver boots af through
# the driver in a uniquely-named container sandbox (#1171) and attaches you to
# the live session to drive it by hand (it prints its teardown command);
# tui-driver-selftest runs the acceptance scenario (boot → 2 instances →
# select → pane → interactive → type → attach/detach → assert selection + no
# orphan clients) in an EPHEMERAL sandbox that is torn down automatically.
# See docs/tui-manual-testing.md.
tui-driver:
	scripts/testbox.sh drive

tui-driver-selftest:
	scripts/testbox.sh selftest

# (Re)build the toolchain image only.
testbox-image:
	scripts/testbox.sh build
