package commands

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/sachiniyer/agent-factory/daemon"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// genDocsCmd regenerates the autogenerated docs reference pages so they can
// never drift from the code. It walks the live Cobra command tree (the same
// rootCmd `af` runs) to emit the CLI reference, and reads the daemon's HTTP
// route catalog (daemon.HTTPRoutes, the #1029 single source of truth) to emit
// the HTTP API reference. It is hidden from `af --help` because it is a
// dev/CI tool, not a user command: scripts/gen-docs.sh runs it and a CI check
// fails if the committed output differs (see .github/workflows/docs.yml).
var genDocsCmd = &cobra.Command{
	Use:    "gen-docs <output-dir>",
	Short:  "Regenerate the autogenerated docs reference pages (CLI + HTTP API)",
	Hidden: true,
	Args:   cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		dir := args[0]
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("failed to create output dir %q: %w", dir, err)
		}
		if err := writeCLIReference(filepath.Join(dir, "cli.md")); err != nil {
			return err
		}
		if err := writeAPIReference(filepath.Join(dir, "api.md")); err != nil {
			return err
		}
		fmt.Fprintf(cmd.OutOrStdout(), "wrote %s and %s\n",
			filepath.Join(dir, "cli.md"), filepath.Join(dir, "api.md"))
		return nil
	},
}

func init() {
	rootCmd.AddCommand(genDocsCmd)
}

// genBanner marks a file as machine-generated. It carries no version or
// timestamp so regenerating an unchanged tree produces byte-identical output —
// the property the CI staleness check depends on.
const genBanner = "<!-- Generated by `af gen-docs` — DO NOT EDIT. " +
	"Regenerate with scripts/gen-docs.sh. -->\n\n"

// writeCLIReference walks the whole `af` command tree and renders one
// consolidated Markdown page: every command, its description, usage, and flags.
// Commands and flags are emitted in a stable (alphabetical) order so the output
// is deterministic regardless of AddCommand order.
func writeCLIReference(path string) error {
	var b strings.Builder
	b.WriteString(genBanner)
	b.WriteString("# CLI reference\n\n")
	b.WriteString("A complete, generated reference for every `af` command and flag, " +
		"produced from the Cobra command tree. This page is regenerated by " +
		"`scripts/gen-docs.sh` and verified in CI, so it never drifts from the " +
		"binary — do not edit it by hand.\n\n")
	b.WriteString("Run `af <command> --help` for the same information at the terminal. " +
		"For a narrative, task-oriented tour of the CLI see the " +
		"[CLI guide](../cli.md).\n\n")

	cmds := collectCommands(rootCmd)

	// Table of contents.
	b.WriteString("## Commands\n\n")
	for _, c := range cmds {
		path := c.CommandPath()
		b.WriteString(fmt.Sprintf("- [`%s`](#%s) — %s\n", path, headingAnchor(path), oneLine(c.Short)))
	}
	b.WriteString("\n")

	for _, c := range cmds {
		renderCommand(&b, c)
	}

	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// collectCommands returns the command and all of its descendants (excluding
// hidden commands and the auto-generated `help` command) in a deterministic,
// depth-first, alphabetical-by-name order.
func collectCommands(root *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		if c.Hidden || c.Name() == "help" {
			return
		}
		out = append(out, c)
		children := append([]*cobra.Command(nil), c.Commands()...)
		sort.Slice(children, func(i, j int) bool { return children[i].Name() < children[j].Name() })
		for _, ch := range children {
			walk(ch)
		}
	}
	walk(root)
	return out
}

// renderCommand appends one command's section: heading, description, usage,
// subcommand index, and flag tables.
func renderCommand(b *strings.Builder, c *cobra.Command) {
	b.WriteString(fmt.Sprintf("## %s\n\n", c.CommandPath()))

	if c.Short != "" {
		b.WriteString(oneLine(c.Short) + "\n\n")
	}
	// Only print Long when it adds information beyond Short.
	if long := strings.TrimSpace(c.Long); long != "" && long != strings.TrimSpace(c.Short) {
		b.WriteString(long + "\n\n")
	}

	b.WriteString("```\n")
	b.WriteString(c.UseLine() + "\n")
	b.WriteString("```\n\n")

	if aliases := c.Aliases; len(aliases) > 0 {
		b.WriteString(fmt.Sprintf("**Aliases:** %s\n\n", strings.Join(backtickAll(aliases), ", ")))
	}

	// Subcommand index (skip hidden / help).
	var subs []*cobra.Command
	for _, ch := range c.Commands() {
		if ch.Hidden || ch.Name() == "help" {
			continue
		}
		subs = append(subs, ch)
	}
	sort.Slice(subs, func(i, j int) bool { return subs[i].Name() < subs[j].Name() })
	if len(subs) > 0 {
		b.WriteString("**Subcommands**\n\n")
		for _, ch := range subs {
			path := ch.CommandPath()
			b.WriteString(fmt.Sprintf("- [`%s`](#%s) — %s\n", path, headingAnchor(path), oneLine(ch.Short)))
		}
		b.WriteString("\n")
	}

	renderFlags(b, "Flags", c.NonInheritedFlags())
	renderFlags(b, "Global flags", c.InheritedFlags())
}

// renderFlags appends a flag table for the visible flags in fs, or nothing if
// there are none. Flag rows are ordered by pflag's default lexical sort, so the
// output is stable across runs.
func renderFlags(b *strings.Builder, title string, fs *pflag.FlagSet) {
	var rows []string
	fs.VisitAll(func(f *pflag.Flag) {
		if f.Hidden || f.Name == "help" {
			return
		}
		name := "`--" + f.Name + "`"
		if f.Shorthand != "" {
			name = "`-" + f.Shorthand + "`, " + name
		}
		typ := f.Value.Type()
		if typ == "bool" {
			typ = ""
		}
		def := ""
		if f.DefValue != "" && f.DefValue != "false" && f.DefValue != "[]" {
			def = fmt.Sprintf(" (default `%s`)", f.DefValue)
		}
		typeCol := ""
		if typ != "" {
			typeCol = "`" + typ + "`"
		}
		rows = append(rows, fmt.Sprintf("| %s | %s | %s%s |", name, typeCol, mdEscape(oneLine(f.Usage)), def))
	})
	if len(rows) == 0 {
		return
	}
	b.WriteString(fmt.Sprintf("**%s**\n\n", title))
	b.WriteString("| Flag | Type | Description |\n")
	b.WriteString("|------|------|-------------|\n")
	b.WriteString(strings.Join(rows, "\n"))
	b.WriteString("\n\n")
}

// writeAPIReference renders the HTTP/JSON API route catalog from
// daemon.HTTPRoutes() — the single source of truth the daemon's mux and the
// `af api` command both read. Only the enumerated route table is generated
// here; the transport, auth, envelope, and status-code prose lives in the
// hand-written HTTP API guide (docs/http-api.md).
func writeAPIReference(path string) error {
	routes := daemon.HTTPRoutes()

	var b strings.Builder
	b.WriteString(genBanner)
	b.WriteString("# HTTP API reference\n\n")
	b.WriteString("Every endpoint the Agent Factory daemon serves over its local Unix " +
		"socket, generated from the daemon's route catalog (the same table the " +
		"`af api` command prints). This page is regenerated by `scripts/gen-docs.sh` " +
		"and verified in CI — do not edit it by hand.\n\n")
	b.WriteString("For the transport, socket path, authentication model, response " +
		"envelope, and status codes, see the [HTTP API guide](../http-api.md). " +
		"Run `af api` to print this catalog with a ready-to-run curl example for " +
		"each route and the resolved socket path for your machine.\n\n")

	b.WriteString("## Endpoints\n\n")
	b.WriteString("Request fields are the JSON keys of each route's request body; " +
		"a `—` means the route takes no body (or an empty `{}`).\n\n")
	b.WriteString("| Method | Path | Request fields | Description |\n")
	b.WriteString("|--------|------|----------------|-------------|\n")
	for _, r := range routes {
		fields := "—"
		if len(r.RequestFields) > 0 {
			fields = strings.Join(backtickAll(r.RequestFields), ", ")
		}
		b.WriteString(fmt.Sprintf("| `%s` | `%s` | %s | %s |\n",
			r.Method, r.Path, fields, mdEscape(r.Description)))
	}
	b.WriteString("\n")

	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// oneLine collapses internal whitespace/newlines to single spaces so a value
// renders on one Markdown line (e.g. in a table cell or list item).
func oneLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

// mdEscape escapes the Markdown table delimiter so descriptions containing a
// pipe do not break table rendering.
func mdEscape(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}

// headingAnchor derives the GitHub/MkDocs slug for a heading whose text is a
// command path like "af sessions create" → "af-sessions-create".
func headingAnchor(heading string) string {
	return strings.ReplaceAll(strings.ToLower(heading), " ", "-")
}

// backtickAll wraps each string in inline-code backticks.
func backtickAll(ss []string) []string {
	out := make([]string, len(ss))
	for i, s := range ss {
		out[i] = "`" + s + "`"
	}
	return out
}
