package commands

import (
	"crypto/sha256"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/sachiniyer/agent-factory/session"
)

// This file generates the installable per-agent plugin artifacts committed to
// the repo (#2172): the Codex plugin and its marketplace, the Claude Code
// plugin and its marketplace, and the portable skill directories for gemini and
// amp. Every one of them carries the SAME af usage guidance —
// session.AfPluginUsageReference, the plugin-framed rendering of the canonical
// afUsageReference — so a user who installs the plugin for their agent gets
// exactly what af injects into the agents it launches itself, and no copy can
// drift from the source.
//
// It lives in commands/ rather than session/ for one reason: the generator is
// wired into `af gen-docs`, which walks the live Cobra tree, and session/
// deliberately imports nothing but config/log. commands/ may import session to
// read the text; session/ may not import the command tree.
//
// Everything under plugins/ and both marketplace files are OUTPUT. Hand-edits
// are reverted by the next `scripts/gen-docs.sh` and fail the CI drift gate
// (.github/workflows/docs.yml) and TestGeneratedPluginsAreCommitted.

const (
	// pluginVersionSeed breaks the version/content cycle while deriving the real
	// manifest version. Hash the complete tree rendered with this fixed seed,
	// then render once more with the content-derived version (#2179 review).
	pluginVersionSeed = "0.0.0"

	// Major 3 sorts after the unordered 2.<hash>.<hash> scheme shipped by #2243.
	pluginVersionMajor = 3

	// agentFactoryModule is the ownership proof writeAgentPlugins requires before
	// its first write or prune. A random directory containing any go.mod is not an
	// af checkout and must never become a destructive target (#2179 review).
	agentFactoryModule = "github.com/sachiniyer/agent-factory"

	// pluginsDir is the committed output root for the per-agent plugins,
	// relative to the repo root.
	pluginsDir = "plugins"

	// pluginLicense mirrors LICENSE.md.
	pluginLicense = "AGPL-3.0"

	// pluginCategory is the marketplace display bucket both Codex and the
	// generated README use.
	pluginCategory = "Developer Tools"
)

// pluginReleaseDigests is an append-only release ledger. Its length is the
// monotonic SemVer minor: a seeded payload/path/mode change must append the new
// digest, which advances ordering automatically. pluginContentVersion refuses
// to generate when the final entry does not match, so the ordinary fix for a
// changed payload cannot update its identity without also moving forward.
var pluginReleaseDigests = []string{
	"951d1d7a412f6c4a28b9498c7b16bda79ff6fad12c5b40963b6cf68f637fcf91", // 3.1
	"d5bf3050bea0bcdbcd41e436738b56d2dd4e25e82b508a751e3c2d1435473f09", // 3.2
	"fb450d6ee2a3cf923ace4ef7dd693b5d9790bb52ec33328bc242fea910f0be95", // 3.3 — instance/session/tab/pane model + dispatched-parent escalation + tightened web-tab guidance (#2473)
}

// pluginGenBanner marks a generated Markdown/shell artifact. Like genBanner it
// carries no version or timestamp, so regenerating an unchanged tree is
// byte-identical — the property the drift gate depends on. JSON manifests get no
// banner: they have no comment syntax, and both Codex and Claude Code validate
// the manifest against a closed field set, so an invented "_generated" key is a
// real risk for no gain.
const pluginGenBanner = "Generated by `af gen-docs --plugin-root` — DO NOT EDIT. " +
	"Regenerate with scripts/gen-docs.sh."

// pluginFile is one generated artifact, addressed relative to the repo root.
type pluginFile struct {
	path    string // slash-separated, relative to the repo root
	content string
	mode    os.FileMode
}

// pluginAgent is one agent's packaging of the af skill. Adding an agent is a
// new entry in pluginAgents: name it, say how a user installs it, and return
// the files. The skill text itself is never per-agent — afSkillMarkdown is
// shared, so a new agent cannot introduce a fifth copy of the usage guidance.
type pluginAgent struct {
	// name is the agent as af names it elsewhere (config program names).
	name string
	// packaging is one line for the generated README: how a user installs it.
	packaging string
	// install is the copy-pasteable install command(s) for the README, or ""
	// when the packaging is a plain copy documented in packaging.
	install string
	// files returns every artifact this agent owns, repo-root-relative.
	files func(version string) []pluginFile
}

// pluginAgents is the agent table. Codex and Claude Code have verified plugin
// manifests and marketplace formats, so they get real, installable plugins.
// gemini and amp get the portable skill directory — the exact shape their CLIs
// discover, and for gemini the exact shape `gemini skills install` consumes —
// but NO invented manifest: neither has a plugin/extension packaging for af
// that was verified against the tool, and guessing a schema we cannot check is
// how a "supported" install path silently stops working. See
// docs/agent-plugins.md for the packaging follow-ups.
var pluginAgents = []pluginAgent{
	{
		name:      "codex",
		packaging: "Codex plugin, served from this repo's marketplace (`.agents/plugins/marketplace.json`).",
		install: "codex plugin marketplace add sachiniyer/agent-factory\n" +
			"codex plugin add " + session.AfSkillName + "@" + session.AfSkillName,
		files: codexPluginFiles,
	},
	{
		name:      "claude",
		packaging: "Claude Code plugin, served from this repo's marketplace (`.claude-plugin/marketplace.json`).",
		install: "claude plugin marketplace add sachiniyer/agent-factory\n" +
			"claude plugin install " + session.AfSkillName + "@" + session.AfSkillName,
		files: claudePluginFiles,
	},
	{
		name: "gemini",
		packaging: "Skill directory. `gemini skills install` reads it straight out of the repo; " +
			"an installable Gemini CLI *extension* is not shipped yet (packaging unverified).",
		install: "gemini skills install https://github.com/sachiniyer/agent-factory --path " +
			pluginsDir + "/gemini/" + session.AfSkillName,
		files: geminiSkillFiles,
	},
	{
		name: "amp",
		packaging: "Skill directory copied from a clone into Amp's documented `.agents/skills/` project directory. " +
			"Amp has no skill-install command or marketplace.",
		install: "git clone https://github.com/sachiniyer/agent-factory\n" +
			"mkdir -p .agents/skills\n" +
			"cp -R agent-factory/" + pluginsDir + "/amp/" + session.AfSkillName + " .agents/skills/",
		files: ampSkillFiles,
	},
}

// afSkillMarkdown is the SKILL.md every agent's plugin carries: name +
// description frontmatter (the only fields codex, claude, gemini and amp all
// require) over the plugin-framed af usage reference.
//
// The body is session.AfPluginUsageReference, never afUsageReference: the
// canonical text opens with "You are running inside Agent Factory (af)", which
// is false for someone who installed this plugin into an agent af did not
// launch. session/systemprompt.go swaps the framing and keeps the body shared;
// TestGeneratedSkillIsReframed locks that the false opening never ships here.
func afSkillMarkdown() string {
	return "---\n" +
		"name: " + session.AfSkillName + "\n" +
		"description: " + session.AfSkillDescription + "\n" +
		"---\n" +
		"<!-- " + pluginGenBanner + " -->\n" +
		"\n" +
		session.AfPluginUsageReference + "\n"
}

// pluginAuthor is the shared author/owner block.
type pluginAuthor struct {
	Name string `json:"name"`
	URL  string `json:"url,omitempty"`
}

func afPluginAuthor() pluginAuthor {
	return pluginAuthor{Name: session.AfPluginAuthorName, URL: session.AfPluginHomepage}
}

// pluginKeywords are the discovery tags every manifest carries.
func pluginKeywords() []string {
	return []string{"agents", "worktrees", "tmux", "automation", "sessions"}
}

// ---------------------------------------------------------------- codex

// codexManifest is `.codex-plugin/plugin.json`. Field set and path conventions
// are from the Codex plugin manifest reference (verified against codex-cli
// 0.144.6, which installs this manifest as written): relative component paths
// begin with "./", only plugin.json belongs in .codex-plugin/, and skills/,
// hooks/ and assets/ sit at the plugin root.
type codexManifest struct {
	Name        string         `json:"name"`
	Version     string         `json:"version"`
	Description string         `json:"description"`
	Author      pluginAuthor   `json:"author"`
	Homepage    string         `json:"homepage"`
	Repository  string         `json:"repository"`
	License     string         `json:"license"`
	Keywords    []string       `json:"keywords"`
	Skills      string         `json:"skills"`
	Hooks       string         `json:"hooks"`
	Interface   codexInterface `json:"interface"`
}

// codexInterface is the manifest's presentation block. defaultPrompt is capped
// at three entries of at most 128 characters by Codex; entries past the third
// are dropped and longer ones truncated, so keep them short.
type codexInterface struct {
	DisplayName      string   `json:"displayName"`
	ShortDescription string   `json:"shortDescription"`
	LongDescription  string   `json:"longDescription"`
	DeveloperName    string   `json:"developerName"`
	Category         string   `json:"category"`
	WebsiteURL       string   `json:"websiteURL"`
	DefaultPrompt    []string `json:"defaultPrompt"`
}

// codexMarketplace is `.agents/plugins/marketplace.json` — the repo-scoped
// catalog a user adds with `codex plugin marketplace add sachiniyer/agent-factory`.
type codexMarketplace struct {
	Name      string                    `json:"name"`
	Interface codexMarketplaceInterface `json:"interface"`
	Plugins   []codexMarketplacePlugin  `json:"plugins"`
}

type codexMarketplaceInterface struct {
	DisplayName string `json:"displayName"`
}

type codexMarketplacePlugin struct {
	Name     string                 `json:"name"`
	Source   codexMarketplaceSource `json:"source"`
	Policy   codexMarketplacePolicy `json:"policy"`
	Category string                 `json:"category"`
}

// codexMarketplaceSource uses the "local" source kind: the plugin lives in the
// same repo as the marketplace, and Codex resolves the path against the
// marketplace root (the directory holding .agents/). The path must begin with
// "./" and stay inside that root.
type codexMarketplaceSource struct {
	Source string `json:"source"`
	Path   string `json:"path"`
}

type codexMarketplacePolicy struct {
	Installation   string `json:"installation"`
	Authentication string `json:"authentication"`
}

// codexPluginRoot is the Codex plugin's root, relative to the repo root. The
// leaf is the plugin name because Codex's marketplace convention is that the
// directory, the manifest `name`, and the marketplace entry `name` all match.
const codexPluginRoot = pluginsDir + "/codex/" + session.AfSkillName

func codexPluginFiles(version string) []pluginFile {
	manifest := codexManifest{
		Name:        session.AfSkillName,
		Version:     version,
		Description: session.AfPluginDescription,
		Author:      afPluginAuthor(),
		Homepage:    session.AfPluginHomepage,
		Repository:  session.AfPluginHomepage,
		License:     pluginLicense,
		Keywords:    pluginKeywords(),
		Skills:      "./skills/",
		Hooks:       "./hooks/hooks.json",
		Interface: codexInterface{
			DisplayName:      "Agent Factory",
			ShortDescription: "Run and schedule coding agents in isolated git worktrees",
			LongDescription: "Agent Factory (af) runs each AI coding agent in its own git worktree " +
				"and tmux session. This plugin teaches Codex to drive the af CLI — create and " +
				"prompt sessions, watch and preview their output, and schedule recurring tasks — " +
				"and checks at session start whether af is installed. It does not install af.",
			DeveloperName: session.AfPluginAuthorName,
			Category:      pluginCategory,
			WebsiteURL:    session.AfPluginHomepage,
			DefaultPrompt: []string{
				"Start an af session that fixes the failing test in this repo.",
				"List my af sessions and preview the one that looks stuck.",
				"Schedule an af task to triage new issues every morning.",
			},
		},
	}

	marketplace := codexMarketplace{
		Name:      session.AfSkillName,
		Interface: codexMarketplaceInterface{DisplayName: "Agent Factory"},
		Plugins: []codexMarketplacePlugin{{
			Name:     session.AfSkillName,
			Source:   codexMarketplaceSource{Source: "local", Path: "./" + codexPluginRoot},
			Policy:   codexMarketplacePolicy{Installation: "AVAILABLE", Authentication: "ON_INSTALL"},
			Category: pluginCategory,
		}},
	}

	return []pluginFile{
		{path: codexPluginRoot + "/.codex-plugin/plugin.json", content: mustJSON(manifest)},
		{path: codexPluginRoot + "/skills/" + session.AfSkillName + "/SKILL.md", content: afSkillMarkdown()},
		{path: codexPluginRoot + "/hooks/hooks.json", content: mustJSON(codexHooks())},
		{path: codexPluginRoot + "/hooks/af-preflight.sh", content: afPreflightHook(), mode: 0o755},
		{path: codexPluginRoot + "/hooks/guard-tmux.sh", content: codexTmuxGuardHook(), mode: 0o755},
		{path: ".agents/plugins/marketplace.json", content: mustJSON(marketplace)},
	}
}

// codexHooks declares the plugin's optional lifecycle hooks. Codex does not
// trust plugin hooks until the user reviews and accepts their exact definition;
// once trusted, PreToolUse is the production delivery seam for the same native
// tmux policy af injects into Claude sessions.
func codexHooks() map[string]any {
	return map[string]any{
		"hooks": map[string]any{
			"SessionStart": []any{
				map[string]any{
					"hooks": []any{
						map[string]any{
							"type":          "command",
							"command":       `bash "${PLUGIN_ROOT}/hooks/af-preflight.sh"`,
							"statusMessage": "Checking for the af CLI",
						},
					},
				},
			},
			"PreToolUse": []any{
				map[string]any{
					"matcher": "Bash",
					"hooks": []any{
						map[string]any{
							"type":          "command",
							"command":       `if [ ! -x "${PLUGIN_ROOT}/hooks/guard-tmux.sh" ]; then echo 'Agent Factory tmux safety guard is unavailable; refusing the Bash command.' >&2; exit 2; fi; "${PLUGIN_ROOT}/hooks/guard-tmux.sh"`,
							"statusMessage": "Checking tmux command safety",
						},
					},
				},
			},
		},
	}
}

// codexTmuxGuardHook delegates to af's agent-neutral native policy. Unlike the
// runtime Claude plugin, an installable Codex plugin cannot pin the af binary
// that generated it, so it resolves the user's installed af from PATH once and
// invokes that exact path. Codex treats exit 2 from PreToolUse as a denial;
// missing or broken policy delivery therefore fails closed instead of turning
// a guard failure into permission to tear down the shared tmux server.
func codexTmuxGuardHook() string {
	return "#!/usr/bin/env bash\n" +
		"# " + pluginGenBanner + "\n" +
		"set -u\n" +
		"\n" +
		"guard_binary=$(type -P af || true)\n" +
		"if [[ -z \"$guard_binary\" || ! -x \"$guard_binary\" ]]; then\n" +
		"\techo 'Agent Factory tmux safety guard binary is unavailable; refusing the Bash command.' >&2\n" +
		"\texit 2\n" +
		"fi\n" +
		"\n" +
		"\"$guard_binary\" hook-guard-tmux\n" +
		"status=$?\n" +
		"if [[ \"$status\" -ne 0 ]]; then\n" +
		"\techo 'Agent Factory tmux safety guard failed; refusing the Bash command.' >&2\n" +
		"\texit 2\n" +
		"fi\n"
}

// afPreflightHook reports whether af is on PATH, and nothing else.
//
// It deliberately does NOT download or install anything. A plugin hook runs as
// the user. Af verifies release checksums, but those checksums are unsigned and
// arrive through the same release channel as the archive, so they protect
// against corruption rather than a compromised publisher or channel.
// Fetch-and-execute from inside an agent session remains the wrong shape at any
// convenience — see #2172 and #2174. Detect and instruct.
func afPreflightHook() string {
	return "#!/usr/bin/env bash\n" +
		"# " + pluginGenBanner + "\n" +
		"#\n" +
		"# Report whether the af CLI is on PATH. Read-only on purpose: this hook never\n" +
		"# downloads or installs anything (see docs/agent-plugins.md).\n" +
		"set -euo pipefail\n" +
		"\n" +
		"if command -v af >/dev/null 2>&1; then\n" +
		"\t# `af version` can print a second \"an upgrade is available\" line; the\n" +
		"\t# hook only wants the version itself.\n" +
		"\tversion=$(af version 2>/dev/null | head -n 1)\n" +
		"\techo \"${version:-af (version unknown)} is available.\"\n" +
		"else\n" +
		"\techo \"af is not installed. Install it with:\"\n" +
		"\techo \"  " + session.AfInstallCommand + "\"\n" +
		"fi\n"
}

// ---------------------------------------------------------------- claude

// claudeManifest is `.claude-plugin/plugin.json`. Verified against the claude
// CLI's own marketplace/install path (see docs/agent-plugins.md); it is the
// same identity af writes into the runtime plugin dir it hands its own claude
// sessions (session/plugin.go), plus the version/URLs a marketplace listing
// needs.
type claudeManifest struct {
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Version     string       `json:"version"`
	Author      pluginAuthor `json:"author"`
	Homepage    string       `json:"homepage"`
	Repository  string       `json:"repository"`
	License     string       `json:"license"`
	Keywords    []string     `json:"keywords"`
}

// claudeMarketplace is `.claude-plugin/marketplace.json`, the catalog a user
// adds with `claude plugin marketplace add sachiniyer/agent-factory`.
type claudeMarketplace struct {
	Name    string                    `json:"name"`
	Owner   pluginAuthor              `json:"owner"`
	Plugins []claudeMarketplacePlugin `json:"plugins"`
}

type claudeMarketplacePlugin struct {
	Name        string `json:"name"`
	Source      string `json:"source"`
	Description string `json:"description"`
	Version     string `json:"version"`
}

const claudePluginRoot = pluginsDir + "/claude/" + session.AfSkillName

func claudePluginFiles(version string) []pluginFile {
	manifest := claudeManifest{
		Name:        session.AfSkillName,
		Description: session.AfPluginDescription,
		Version:     version,
		Author:      afPluginAuthor(),
		Homepage:    session.AfPluginHomepage,
		Repository:  session.AfPluginHomepage,
		License:     pluginLicense,
		Keywords:    pluginKeywords(),
	}

	marketplace := claudeMarketplace{
		Name:  session.AfSkillName,
		Owner: afPluginAuthor(),
		Plugins: []claudeMarketplacePlugin{{
			Name:        session.AfSkillName,
			Source:      "./" + claudePluginRoot,
			Description: session.AfPluginDescription,
			Version:     version,
		}},
	}

	return []pluginFile{
		{path: claudePluginRoot + "/.claude-plugin/plugin.json", content: mustJSON(manifest)},
		{path: claudePluginRoot + "/skills/" + session.AfSkillName + "/SKILL.md", content: afSkillMarkdown()},
		{path: ".claude-plugin/marketplace.json", content: mustJSON(marketplace)},
	}
}

// ------------------------------------------------------- gemini and amp

// geminiSkillFiles emits the portable skill directory. It is exactly the shape
// gemini discovers under ~/.gemini/skills and exactly what `gemini skills
// install --path` copies out of a repo, so no manifest is invented: a Gemini
// CLI *extension* (gemini-extension.json) would be a second, unverified
// packaging of the same text.
func geminiSkillFiles(_ string) []pluginFile {
	return []pluginFile{
		{path: pluginsDir + "/gemini/" + session.AfSkillName + "/SKILL.md", content: afSkillMarkdown()},
	}
}

// ampSkillFiles emits the portable skill directory Amp discovers under the
// documented project/user skill roots. Amp no longer exposes add/remove/update
// skill subcommands, so installation is an ordinary directory copy (#2179
// review). No marketplace or invented manifest is emitted.
func ampSkillFiles(_ string) []pluginFile {
	return []pluginFile{
		{path: pluginsDir + "/amp/" + session.AfSkillName + "/SKILL.md", content: afSkillMarkdown()},
	}
}

// ---------------------------------------------------------------- emit

// pluginsReadme is the generated index for plugins/. It is generated too, so
// the agent table and the install instructions cannot disagree.
func pluginsReadme() string {
	var b strings.Builder
	b.WriteString("<!-- " + pluginGenBanner + " -->\n\n")
	b.WriteString("# Agent plugins\n\n")
	b.WriteString("Installable packagings of one thing: the `" + session.AfSkillName +
		"` skill that teaches an AI coding agent to drive the `af` CLI. Install the one " +
		"for your agent and it can run and schedule af sessions in any repo — including " +
		"sessions af did not launch.\n\n")
	b.WriteString("Every file in this directory is **generated** from " +
		"`session.AfPluginUsageReference`, the same af usage guidance af injects into " +
		"the agents it launches itself. Edit `session/systemprompt.go` and run " +
		"`scripts/gen-docs.sh`; hand-edits here are reverted and fail CI.\n\n")
	b.WriteString("The plugin does **not** install `af`. Install it first:\n\n")
	b.WriteString("```\n" + session.AfInstallCommand + "\n```\n\n")

	for _, a := range pluginAgents {
		b.WriteString("## " + a.name + "\n\n")
		b.WriteString(a.packaging + "\n\n")
		if a.install != "" {
			b.WriteString("```\n" + a.install + "\n```\n\n")
		}
	}

	b.WriteString("See [docs/agent-plugins.md](../docs/agent-plugins.md) for what each " +
		"packaging does and does not do.\n")
	return b.String()
}

// generatedPluginFiles returns every generated artifact with a version bound to
// the complete version-neutral tree. The ordered release serial makes every
// later release greater under SemVer; the pinned digest makes generation fail
// until a payload change advances that serial (#2179/#2243 review).
func generatedPluginFiles() []pluginFile {
	seed := generatedPluginFilesAtVersion(pluginVersionSeed)
	return generatedPluginFilesAtVersion(pluginContentVersion(seed))
}

// generatedPluginFilesAtVersion is the single enumeration the content-version
// pass, writer, pruner, and drift test read.
func generatedPluginFilesAtVersion(version string) []pluginFile {
	files := []pluginFile{{path: pluginsDir + "/README.md", content: pluginsReadme()}}
	for _, a := range pluginAgents {
		files = append(files, a.files(version)...)
	}
	for i := range files {
		if files[i].mode == 0 {
			files[i].mode = 0o644
		}
	}
	sort.Slice(files, func(i, j int) bool { return files[i].path < files[j].path })
	return files
}

// pluginContentVersion validates the complete seeded tree against the release
// pin, then gives it a monotonic SemVer identity. Minor is the ordered release
// serial; patch plus build metadata retain a 64-bit content address. A payload
// change without an explicit serial bump panics before any generated file is
// written, turning the easy-to-forget cache invariant into a hard generation
// gate rather than another maintainer convention.
func pluginContentVersion(files []pluginFile) string {
	sum := pluginContentSum(files)
	digest := fmt.Sprintf("%x", sum)
	release := uint64(len(pluginReleaseDigests))
	if release == 0 || digest != pluginReleaseDigests[len(pluginReleaseDigests)-1] {
		panic(fmt.Sprintf(
			"plugin generator: release %d content digest is %s; append it to pluginReleaseDigests (do not replace existing entries) to advance the plugin version",
			release, digest,
		))
	}
	return pluginVersionForRelease(release, sum)
}

func pluginContentSum(files []pluginFile) [sha256.Size]byte {
	h := sha256.New()
	for _, f := range files {
		_, _ = fmt.Fprintf(h, "%s\x00%o\x00%s\x00", f.path, f.mode, f.content)
	}
	var sum [sha256.Size]byte
	copy(sum[:], h.Sum(nil))
	return sum
}

func pluginVersionForRelease(release uint64, sum [sha256.Size]byte) string {
	return fmt.Sprintf("%d.%d.%d+sha256.%x",
		pluginVersionMajor,
		release,
		binary.BigEndian.Uint32(sum[:4]),
		sum[:8],
	)
}

// mustJSON renders a manifest as indented JSON with a trailing newline. The
// input is always a literal built above, so a marshal failure is a programming
// error, not a runtime condition.
func mustJSON(v any) string {
	out, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		panic(fmt.Sprintf("plugin generator: marshaling %T: %v", v, err))
	}
	return string(out) + "\n"
}

// writeAgentPlugins writes every generated artifact under root and prunes any
// stale file left under plugins/ by an earlier revision of the table, so
// deleting an agent removes its artifacts instead of orphaning them (the same
// property session.ensurePluginDir gives the runtime plugin dir).
//
// root must be THIS af checkout — the go.mod module directive is validated
// before the first write. The pruner deletes files under plugins/ only; the two
// marketplace files are named, single, and overwritten in place.
func writeAgentPlugins(root string) ([]string, error) {
	goModPath := filepath.Join(root, "go.mod")
	goMod, err := os.ReadFile(goModPath)
	if err != nil {
		return nil, fmt.Errorf("--plugin-root %q is not an af checkout (cannot read go.mod): %w", root, err)
	}
	module := goModulePath(goMod)
	if module != agentFactoryModule {
		return nil, fmt.Errorf("--plugin-root %q is not an af checkout (go.mod module is %q, want %q)", root, module, agentFactoryModule)
	}

	files := generatedPluginFiles()
	written := make(map[string]bool, len(files))
	paths := make([]string, 0, len(files))

	for _, f := range files {
		abs := filepath.Join(root, filepath.FromSlash(f.path))
		if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
			return nil, fmt.Errorf("failed to create %s: %w", filepath.Dir(abs), err)
		}
		if err := os.WriteFile(abs, []byte(f.content), f.mode); err != nil {
			return nil, fmt.Errorf("failed to write %s: %w", abs, err)
		}
		// WriteFile does not change the mode of an existing file, so a mode
		// change (or a file that arrived with the wrong bits) is applied
		// explicitly — the preflight hook has to stay executable.
		if err := os.Chmod(abs, f.mode); err != nil {
			return nil, fmt.Errorf("failed to chmod %s: %w", abs, err)
		}
		written[abs] = true
		paths = append(paths, f.path)
	}

	if err := prunePluginTree(filepath.Join(root, pluginsDir), written); err != nil {
		return nil, err
	}
	return paths, nil
}

// goModulePath reads the module directive without accepting a mere go.mod as
// ownership proof. Quoted module paths are legal, though this repo uses the
// ordinary unquoted form.
func goModulePath(goMod []byte) string {
	for _, line := range strings.Split(string(goMod), "\n") {
		fields := strings.Fields(line)
		if len(fields) < 2 || fields[0] != "module" {
			continue
		}
		return strings.Trim(fields[1], `"`)
	}
	return ""
}

// prunePluginTree removes every file under dir that the generator did not just
// write, then removes the directories left empty. A missing dir is not an error
// (nothing generated yet).
func prunePluginTree(dir string, written map[string]bool) error {
	var dirs []string
	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			dirs = append(dirs, path)
			return nil
		}
		if written[path] {
			return nil
		}
		return os.Remove(path)
	})
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("failed to prune stale plugin artifacts under %s: %w", dir, err)
	}
	// Deepest first, so a directory emptied by the walk above is removed too.
	sort.Sort(sort.Reverse(sort.StringSlice(dirs)))
	for _, d := range dirs {
		if d == dir {
			continue
		}
		_ = os.Remove(d) // fails harmlessly (ENOTEMPTY) when still in use
	}
	return nil
}
