package commands

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/sachiniyer/agent-factory/session"
)

// This file generates the installable per-agent plugin artifacts committed to
// the repo (#2172): the Codex plugin and its marketplace, the Claude Code
// plugin and its marketplace, and the portable skill directories for gemini and
// amp. Every one of them carries the SAME af usage guidance —
// session.AfPluginUsageReference, the plugin-framed rendering of the canonical
// afUsageReference — so a user who installs the plugin for their agent gets
// exactly what af injects into the agents it launches itself, and no copy can
// drift from the source.
//
// It lives in commands/ rather than session/ for one reason: the generator is
// wired into `af gen-docs`, which walks the live Cobra tree, and session/
// deliberately imports nothing but config/log. commands/ may import session to
// read the text; session/ may not import the command tree.
//
// Everything under plugins/ and both marketplace files are OUTPUT. Hand-edits
// are reverted by the next `scripts/gen-docs.sh` and fail the CI drift gate
// (.github/workflows/docs.yml) and TestGeneratedPluginsAreCommitted.

const (
	// agentPluginVersion is the semver carried by every generated plugin
	// manifest. It is deliberately NOT af's own version (main.go, auto-bumped
	// by CI on every release): tying them together would make each release
	// bump rewrite the committed artifacts, so an unrelated release would fail
	// the drift gate. Bump this by hand when the plugin's shape changes.
	agentPluginVersion = "1.0.0"

	// pluginsDir is the committed output root for the per-agent plugins,
	// relative to the repo root.
	pluginsDir = "plugins"

	// pluginLicense mirrors LICENSE.md.
	pluginLicense = "AGPL-3.0"

	// pluginCategory is the marketplace display bucket both Codex and the
	// generated README use.
	pluginCategory = "Developer Tools"
)

// pluginGenBanner marks a generated Markdown/shell artifact. Like genBanner it
// carries no version or timestamp, so regenerating an unchanged tree is
// byte-identical — the property the drift gate depends on. JSON manifests get no
// banner: they have no comment syntax, and both Codex and Claude Code validate
// the manifest against a closed field set, so an invented "_generated" key is a
// real risk for no gain.
const pluginGenBanner = "Generated by `af gen-docs --plugin-root` — DO NOT EDIT. " +
	"Regenerate with scripts/gen-docs.sh."

// pluginFile is one generated artifact, addressed relative to the repo root.
type pluginFile struct {
	path    string // slash-separated, relative to the repo root
	content string
	mode    os.FileMode
}

// pluginAgent is one agent's packaging of the af skill. Adding an agent is a
// new entry in pluginAgents: name it, say how a user installs it, and return
// the files. The skill text itself is never per-agent — afSkillMarkdown is
// shared, so a new agent cannot introduce a fifth copy of the usage guidance.
type pluginAgent struct {
	// name is the agent as af names it elsewhere (config program names).
	name string
	// packaging is one line for the generated README: how a user installs it.
	packaging string
	// install is the copy-pasteable install command(s) for the README, or ""
	// when the packaging is a plain copy documented in packaging.
	install string
	// files returns every artifact this agent owns, repo-root-relative.
	files func() []pluginFile
}

// pluginAgents is the agent table. Codex and Claude Code have verified plugin
// manifests and marketplace formats, so they get real, installable plugins.
// gemini and amp get the portable skill directory — the exact shape their CLIs
// discover, and for gemini the exact shape `gemini skills install` consumes —
// but NO invented manifest: neither has a plugin/extension packaging for af
// that was verified against the tool, and guessing a schema we cannot check is
// how a "supported" install path silently stops working. See
// docs/agent-plugins.md for the packaging follow-ups.
var pluginAgents = []pluginAgent{
	{
		name:      "codex",
		packaging: "Codex plugin, served from this repo's marketplace (`.agents/plugins/marketplace.json`).",
		install: "codex plugin marketplace add sachiniyer/agent-factory\n" +
			"codex plugin add " + session.AfSkillName + "@" + session.AfSkillName,
		files: codexPluginFiles,
	},
	{
		name:      "claude",
		packaging: "Claude Code plugin, served from this repo's marketplace (`.claude-plugin/marketplace.json`).",
		install: "claude plugin marketplace add sachiniyer/agent-factory\n" +
			"claude plugin install " + session.AfSkillName + "@" + session.AfSkillName,
		files: claudePluginFiles,
	},
	{
		name: "gemini",
		packaging: "Skill directory. `gemini skills install` reads it straight out of the repo; " +
			"an installable Gemini CLI *extension* is not shipped yet (packaging unverified).",
		install: "gemini skills install https://github.com/sachiniyer/agent-factory --path " +
			pluginsDir + "/gemini/" + session.AfSkillName,
		files: geminiSkillFiles,
	},
	{
		name: "amp",
		packaging: "Skill directory, installed with `amp skill add` from a clone. amp has no " +
			"marketplace, so there is no one-line remote install.",
		install: "git clone https://github.com/sachiniyer/agent-factory\n" +
			"amp skill add agent-factory/" + pluginsDir + "/amp/" + session.AfSkillName,
		files: ampSkillFiles,
	},
}

// afSkillMarkdown is the SKILL.md every agent's plugin carries: name +
// description frontmatter (the only fields codex, claude, gemini and amp all
// require) over the plugin-framed af usage reference.
//
// The body is session.AfPluginUsageReference, never afUsageReference: the
// canonical text opens with "You are running inside Agent Factory (af)", which
// is false for someone who installed this plugin into an agent af did not
// launch. session/systemprompt.go swaps the framing and keeps the body shared;
// TestGeneratedSkillIsReframed locks that the false opening never ships here.
func afSkillMarkdown() string {
	return "---\n" +
		"name: " + session.AfSkillName + "\n" +
		"description: " + session.AfSkillDescription + "\n" +
		"---\n" +
		"<!-- " + pluginGenBanner + " -->\n" +
		"\n" +
		session.AfPluginUsageReference + "\n"
}

// pluginAuthor is the shared author/owner block.
type pluginAuthor struct {
	Name string `json:"name"`
	URL  string `json:"url,omitempty"`
}

func afPluginAuthor() pluginAuthor {
	return pluginAuthor{Name: session.AfPluginAuthorName, URL: session.AfPluginHomepage}
}

// pluginKeywords are the discovery tags every manifest carries.
func pluginKeywords() []string {
	return []string{"agents", "worktrees", "tmux", "automation", "sessions"}
}

// ---------------------------------------------------------------- codex

// codexManifest is `.codex-plugin/plugin.json`. Field set and path conventions
// are from the Codex plugin manifest reference (verified against codex-cli
// 0.144.6, which installs this manifest as written): relative component paths
// begin with "./", only plugin.json belongs in .codex-plugin/, and skills/,
// hooks/ and assets/ sit at the plugin root.
type codexManifest struct {
	Name        string         `json:"name"`
	Version     string         `json:"version"`
	Description string         `json:"description"`
	Author      pluginAuthor   `json:"author"`
	Homepage    string         `json:"homepage"`
	Repository  string         `json:"repository"`
	License     string         `json:"license"`
	Keywords    []string       `json:"keywords"`
	Skills      string         `json:"skills"`
	Hooks       string         `json:"hooks"`
	Interface   codexInterface `json:"interface"`
}

// codexInterface is the manifest's presentation block. defaultPrompt is capped
// at three entries of at most 128 characters by Codex; entries past the third
// are dropped and longer ones truncated, so keep them short.
type codexInterface struct {
	DisplayName      string   `json:"displayName"`
	ShortDescription string   `json:"shortDescription"`
	LongDescription  string   `json:"longDescription"`
	DeveloperName    string   `json:"developerName"`
	Category         string   `json:"category"`
	WebsiteURL       string   `json:"websiteURL"`
	DefaultPrompt    []string `json:"defaultPrompt"`
}

// codexMarketplace is `.agents/plugins/marketplace.json` — the repo-scoped
// catalog a user adds with `codex plugin marketplace add sachiniyer/agent-factory`.
type codexMarketplace struct {
	Name      string                    `json:"name"`
	Interface codexMarketplaceInterface `json:"interface"`
	Plugins   []codexMarketplacePlugin  `json:"plugins"`
}

type codexMarketplaceInterface struct {
	DisplayName string `json:"displayName"`
}

type codexMarketplacePlugin struct {
	Name     string                 `json:"name"`
	Source   codexMarketplaceSource `json:"source"`
	Policy   codexMarketplacePolicy `json:"policy"`
	Category string                 `json:"category"`
}

// codexMarketplaceSource uses the "local" source kind: the plugin lives in the
// same repo as the marketplace, and Codex resolves the path against the
// marketplace root (the directory holding .agents/). The path must begin with
// "./" and stay inside that root.
type codexMarketplaceSource struct {
	Source string `json:"source"`
	Path   string `json:"path"`
}

type codexMarketplacePolicy struct {
	Installation   string `json:"installation"`
	Authentication string `json:"authentication"`
}

// codexPluginRoot is the Codex plugin's root, relative to the repo root. The
// leaf is the plugin name because Codex's marketplace convention is that the
// directory, the manifest `name`, and the marketplace entry `name` all match.
const codexPluginRoot = pluginsDir + "/codex/" + session.AfSkillName

func codexPluginFiles() []pluginFile {
	manifest := codexManifest{
		Name:        session.AfSkillName,
		Version:     agentPluginVersion,
		Description: session.AfPluginDescription,
		Author:      afPluginAuthor(),
		Homepage:    session.AfPluginHomepage,
		Repository:  session.AfPluginHomepage,
		License:     pluginLicense,
		Keywords:    pluginKeywords(),
		Skills:      "./skills/",
		Hooks:       "./hooks/hooks.json",
		Interface: codexInterface{
			DisplayName:      "Agent Factory",
			ShortDescription: "Run and schedule coding agents in isolated git worktrees",
			LongDescription: "Agent Factory (af) runs each AI coding agent in its own git worktree " +
				"and tmux session. This plugin teaches Codex to drive the af CLI — create and " +
				"prompt sessions, watch and preview their output, and schedule recurring tasks — " +
				"and checks at session start whether af is installed. It does not install af.",
			DeveloperName: session.AfPluginAuthorName,
			Category:      pluginCategory,
			WebsiteURL:    session.AfPluginHomepage,
			DefaultPrompt: []string{
				"Start an af session that fixes the failing test in this repo.",
				"List my af sessions and preview the one that looks stuck.",
				"Schedule an af task to triage new issues every morning.",
			},
		},
	}

	marketplace := codexMarketplace{
		Name:      session.AfSkillName,
		Interface: codexMarketplaceInterface{DisplayName: "Agent Factory"},
		Plugins: []codexMarketplacePlugin{{
			Name:     session.AfSkillName,
			Source:   codexMarketplaceSource{Source: "local", Path: "./" + codexPluginRoot},
			Policy:   codexMarketplacePolicy{Installation: "AVAILABLE", Authentication: "ON_INSTALL"},
			Category: pluginCategory,
		}},
	}

	return []pluginFile{
		{path: codexPluginRoot + "/.codex-plugin/plugin.json", content: mustJSON(manifest)},
		{path: codexPluginRoot + "/skills/" + session.AfSkillName + "/SKILL.md", content: afSkillMarkdown()},
		{path: codexPluginRoot + "/hooks/hooks.json", content: mustJSON(codexHooks())},
		{path: codexPluginRoot + "/hooks/af-preflight.sh", content: afPreflightHook(), mode: 0o755},
		{path: ".agents/plugins/marketplace.json", content: mustJSON(marketplace)},
	}
}

// codexHooks declares the one optional, detect-only lifecycle hook. Codex does
// not trust a plugin's hooks until the user reviews and accepts them, so the
// plugin is fully usable with the hook declined — it only turns "af: command
// not found" three turns in into one clear line at session start.
func codexHooks() map[string]any {
	return map[string]any{
		"hooks": map[string]any{
			"SessionStart": []any{
				map[string]any{
					"hooks": []any{
						map[string]any{
							"type":          "command",
							"command":       `bash "${PLUGIN_ROOT}/hooks/af-preflight.sh"`,
							"statusMessage": "Checking for the af CLI",
						},
					},
				},
			},
		},
	}
}

// afPreflightHook reports whether af is on PATH, and nothing else.
//
// It deliberately does NOT download or install anything. A plugin hook runs as
// the user, and af's releases carry no checksum or signature to verify against
// (install.sh and `af upgrade` both check only that the tarball is a tarball),
// so fetch-and-execute from inside an agent session is the wrong shape at any
// convenience — see #2172 and #2174. Detect and instruct.
func afPreflightHook() string {
	return "#!/usr/bin/env bash\n" +
		"# " + pluginGenBanner + "\n" +
		"#\n" +
		"# Report whether the af CLI is on PATH. Read-only on purpose: this hook never\n" +
		"# downloads or installs anything (see docs/agent-plugins.md).\n" +
		"set -euo pipefail\n" +
		"\n" +
		"if command -v af >/dev/null 2>&1; then\n" +
		"\t# `af version` can print a second \"an upgrade is available\" line; the\n" +
		"\t# hook only wants the version itself.\n" +
		"\tversion=$(af version 2>/dev/null | head -n 1)\n" +
		"\techo \"${version:-af (version unknown)} is available.\"\n" +
		"else\n" +
		"\techo \"af is not installed. Install it with:\"\n" +
		"\techo \"  " + session.AfInstallCommand + "\"\n" +
		"fi\n"
}

// ---------------------------------------------------------------- claude

// claudeManifest is `.claude-plugin/plugin.json`. Verified against the claude
// CLI's own marketplace/install path (see docs/agent-plugins.md); it is the
// same identity af writes into the runtime plugin dir it hands its own claude
// sessions (session/plugin.go), plus the version/URLs a marketplace listing
// needs.
type claudeManifest struct {
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Version     string       `json:"version"`
	Author      pluginAuthor `json:"author"`
	Homepage    string       `json:"homepage"`
	Repository  string       `json:"repository"`
	License     string       `json:"license"`
	Keywords    []string     `json:"keywords"`
}

// claudeMarketplace is `.claude-plugin/marketplace.json`, the catalog a user
// adds with `claude plugin marketplace add sachiniyer/agent-factory`.
type claudeMarketplace struct {
	Name    string                    `json:"name"`
	Owner   pluginAuthor              `json:"owner"`
	Plugins []claudeMarketplacePlugin `json:"plugins"`
}

type claudeMarketplacePlugin struct {
	Name        string `json:"name"`
	Source      string `json:"source"`
	Description string `json:"description"`
	Version     string `json:"version"`
}

const claudePluginRoot = pluginsDir + "/claude/" + session.AfSkillName

func claudePluginFiles() []pluginFile {
	manifest := claudeManifest{
		Name:        session.AfSkillName,
		Description: session.AfPluginDescription,
		Version:     agentPluginVersion,
		Author:      afPluginAuthor(),
		Homepage:    session.AfPluginHomepage,
		Repository:  session.AfPluginHomepage,
		License:     pluginLicense,
		Keywords:    pluginKeywords(),
	}

	marketplace := claudeMarketplace{
		Name:  session.AfSkillName,
		Owner: afPluginAuthor(),
		Plugins: []claudeMarketplacePlugin{{
			Name:        session.AfSkillName,
			Source:      "./" + claudePluginRoot,
			Description: session.AfPluginDescription,
			Version:     agentPluginVersion,
		}},
	}

	return []pluginFile{
		{path: claudePluginRoot + "/.claude-plugin/plugin.json", content: mustJSON(manifest)},
		{path: claudePluginRoot + "/skills/" + session.AfSkillName + "/SKILL.md", content: afSkillMarkdown()},
		{path: ".claude-plugin/marketplace.json", content: mustJSON(marketplace)},
	}
}

// ------------------------------------------------------- gemini and amp

// geminiSkillFiles emits the portable skill directory. It is exactly the shape
// gemini discovers under ~/.gemini/skills and exactly what `gemini skills
// install --path` copies out of a repo, so no manifest is invented: a Gemini
// CLI *extension* (gemini-extension.json) would be a second, unverified
// packaging of the same text.
func geminiSkillFiles() []pluginFile {
	return []pluginFile{
		{path: pluginsDir + "/gemini/" + session.AfSkillName + "/SKILL.md", content: afSkillMarkdown()},
	}
}

// ampSkillFiles emits the portable skill directory. `amp skill add <path>`
// installs it from a clone (verified against the amp CLI), and it is also the
// shape amp discovers under ~/.config/amp/skills — the directory af writes when
// global_agent_skills is on. amp has no marketplace to publish to, so no
// manifest is invented for it.
func ampSkillFiles() []pluginFile {
	return []pluginFile{
		{path: pluginsDir + "/amp/" + session.AfSkillName + "/SKILL.md", content: afSkillMarkdown()},
	}
}

// ---------------------------------------------------------------- emit

// pluginsReadme is the generated index for plugins/. It is generated too, so
// the agent table and the install instructions cannot disagree.
func pluginsReadme() string {
	var b strings.Builder
	b.WriteString("<!-- " + pluginGenBanner + " -->\n\n")
	b.WriteString("# Agent plugins\n\n")
	b.WriteString("Installable packagings of one thing: the `" + session.AfSkillName +
		"` skill that teaches an AI coding agent to drive the `af` CLI. Install the one " +
		"for your agent and it can run and schedule af sessions in any repo — including " +
		"sessions af did not launch.\n\n")
	b.WriteString("Every file in this directory is **generated** from " +
		"`session.AfPluginUsageReference`, the same af usage guidance af injects into " +
		"the agents it launches itself. Edit `session/systemprompt.go` and run " +
		"`scripts/gen-docs.sh`; hand-edits here are reverted and fail CI.\n\n")
	b.WriteString("The plugin does **not** install `af`. Install it first:\n\n")
	b.WriteString("```\n" + session.AfInstallCommand + "\n```\n\n")

	for _, a := range pluginAgents {
		b.WriteString("## " + a.name + "\n\n")
		b.WriteString(a.packaging + "\n\n")
		if a.install != "" {
			b.WriteString("```\n" + a.install + "\n```\n\n")
		}
	}

	b.WriteString("See [docs/agent-plugins.md](../docs/agent-plugins.md) for what each " +
		"packaging does and does not do.\n")
	return b.String()
}

// generatedPluginFiles returns every generated artifact, repo-root-relative and
// sorted by path, with the default mode filled in. It is the single enumeration
// the writer, the pruner and the drift test all read.
func generatedPluginFiles() []pluginFile {
	files := []pluginFile{{path: pluginsDir + "/README.md", content: pluginsReadme()}}
	for _, a := range pluginAgents {
		files = append(files, a.files()...)
	}
	for i := range files {
		if files[i].mode == 0 {
			files[i].mode = 0o644
		}
	}
	sort.Slice(files, func(i, j int) bool { return files[i].path < files[j].path })
	return files
}

// mustJSON renders a manifest as indented JSON with a trailing newline. The
// input is always a literal built above, so a marshal failure is a programming
// error, not a runtime condition.
func mustJSON(v any) string {
	out, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		panic(fmt.Sprintf("plugin generator: marshaling %T: %v", v, err))
	}
	return string(out) + "\n"
}

// writeAgentPlugins writes every generated artifact under root and prunes any
// stale file left under plugins/ by an earlier revision of the table, so
// deleting an agent removes its artifacts instead of orphaning them (the same
// property session.ensurePluginDir gives the runtime plugin dir).
//
// root must be an af checkout — it is verified by the presence of go.mod before
// anything under it is removed. The pruner deletes files under plugins/ only;
// the two marketplace files are named, single, and overwritten in place.
func writeAgentPlugins(root string) ([]string, error) {
	if _, err := os.Stat(filepath.Join(root, "go.mod")); err != nil {
		return nil, fmt.Errorf("--plugin-root %q is not an af checkout (no go.mod): %w", root, err)
	}

	files := generatedPluginFiles()
	written := make(map[string]bool, len(files))
	paths := make([]string, 0, len(files))

	for _, f := range files {
		abs := filepath.Join(root, filepath.FromSlash(f.path))
		if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
			return nil, fmt.Errorf("failed to create %s: %w", filepath.Dir(abs), err)
		}
		if err := os.WriteFile(abs, []byte(f.content), f.mode); err != nil {
			return nil, fmt.Errorf("failed to write %s: %w", abs, err)
		}
		// WriteFile does not change the mode of an existing file, so a mode
		// change (or a file that arrived with the wrong bits) is applied
		// explicitly — the preflight hook has to stay executable.
		if err := os.Chmod(abs, f.mode); err != nil {
			return nil, fmt.Errorf("failed to chmod %s: %w", abs, err)
		}
		written[abs] = true
		paths = append(paths, f.path)
	}

	if err := prunePluginTree(filepath.Join(root, pluginsDir), written); err != nil {
		return nil, err
	}
	return paths, nil
}

// prunePluginTree removes every file under dir that the generator did not just
// write, then removes the directories left empty. A missing dir is not an error
// (nothing generated yet).
func prunePluginTree(dir string, written map[string]bool) error {
	var dirs []string
	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			dirs = append(dirs, path)
			return nil
		}
		if written[path] {
			return nil
		}
		return os.Remove(path)
	})
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("failed to prune stale plugin artifacts under %s: %w", dir, err)
	}
	// Deepest first, so a directory emptied by the walk above is removed too.
	sort.Sort(sort.Reverse(sort.StringSlice(dirs)))
	for _, d := range dirs {
		if d == dir {
			continue
		}
		_ = os.Remove(d) // fails harmlessly (ENOTEMPTY) when still in use
	}
	return nil
}
