#!/usr/bin/env bash
# Generated by `af gen-docs --plugin-root` — DO NOT EDIT. Regenerate with scripts/gen-docs.sh.
#
# Report whether the af CLI is on PATH. Read-only on purpose: this hook never
# downloads or installs anything (see docs/agent-plugins.md).
set -euo pipefail

if command -v af >/dev/null 2>&1; then
	# `af version` can print a second "an upgrade is available" line; the
	# hook only wants the version itself.
	version=$(af version 2>/dev/null | head -n 1)
	echo "${version:-af (version unknown)} is available."
else
	echo "af is not installed. Install it with:"
	echo "  curl -fsSL https://raw.githubusercontent.com/sachiniyer/agent-factory/master/install.sh | sh"
fi
