#!/usr/bin/env bash
# Generated by `af gen-docs --plugin-root` — DO NOT EDIT. Regenerate with scripts/gen-docs.sh.
set -u

guard_binary=$(type -P af || true)
if [[ -z "$guard_binary" || ! -x "$guard_binary" ]]; then
	echo 'Agent Factory tmux safety guard binary is unavailable; refusing the Bash command.' >&2
	exit 2
fi

"$guard_binary" hook-guard-tmux
status=$?
if [[ "$status" -ne 0 ]]; then
	echo 'Agent Factory tmux safety guard failed; refusing the Bash command.' >&2
	exit 2
fi
