package agentproto

// ClientVersionHeader marks a request as machine-generated by an af client (TUI,
// CLI, web) and carries that client's version for diagnostics.
//
// It exists to separate two populations that a strict JSON decoder cannot tell
// apart, because to it both are simply an "unknown field":
//
//   - A REAL af client running a different version than the daemon. The daemon is
//     upgraded INDEPENDENTLY of its clients (#960 makes it the sole writer and
//     `af upgrade` restarts it under live TUIs), so a newer client legitimately
//     sends fields an older daemon has never heard of — `tab_id` on
//     PreviewRequest (#1779), `id` on KillSessionRequest (#1678). The #1029
//     contract declares those additive, so they MUST degrade gracefully rather
//     than hard-fail the request.
//   - A HAND-AUTHORED request (curl, `af api`, a one-off script). Here an unknown
//     field is nearly always a typo, and silently dropping it can WIDEN an RPC's
//     semantics: a typo'd `repo_idd` leaves RepoID empty, turning a one-repo
//     Snapshot into an all-repo Snapshot (#1264/#1273). Those must keep failing
//     loudly.
//
// The header's PRESENCE is the discriminator; its value is diagnostics only, so
// a client that cannot resolve its own version still gets forward-compatible
// decoding. This is deliberately NOT an auth boundary and is not treated as
// trusted input — a caller that sets it by hand simply opts out of typo checking
// in exchange for forward-compatible decoding, which is precisely the trade every
// af client already makes. The worst a spoofer achieves is the decode behavior
// they could get by spelling their fields correctly.
const ClientVersionHeader = "X-AF-Client-Version"
