// Code generated by scripts/gen-design; DO NOT EDIT.
// Package theme is the staged P0 palette. Live ui.Theme remains unchanged until P5.
package theme

import "github.com/charmbracelet/lipgloss"

type State struct {
	Name, Label, Glyph string
	Color              lipgloss.AdaptiveColor
}

// Colors returns fresh semantic light/dark pairs; terminal capability resolution belongs to lipgloss.
func Colors() map[string]lipgloss.AdaptiveColor {
	return map[string]lipgloss.AdaptiveColor{
		"accent":         {Light: "#2d6271", Dark: "#90c4d3"},
		"archived":       {Light: "#4c566a", Dark: "#d8dee9"},
		"border":         {Light: "#657084", Dark: "#a1aaba"},
		"dead":           {Light: "#883b43", Dark: "#e4c8cd"},
		"ink":            {Light: "#2e3440", Dark: "#eceff4"},
		"ink-muted":      {Light: "#4c566a", Dark: "#b7c0ce"},
		"limit-reached":  {Light: "#73436b", Dark: "#dbb9d5"},
		"lost":           {Light: "#705014", Dark: "#ebcb8b"},
		"ready":          {Light: "#405430", Dark: "#d5e2cc"},
		"running":        {Light: "#4c566a", Dark: "#d8dee9"},
		"surface":        {Light: "#f8f9fc", Dark: "#2e3440"},
		"surface-raised": {Light: "#eceff4", Dark: "#434c5e"},
	}
}

// Metrics are terminal cells, rows or flags as documented in design/tokens.json.
func Metrics() map[string]int {
	return map[string]int{
		"radius-control": 0,
		"radius-dialog":  1,
		"space-1":        1,
		"space-2":        1,
		"space-3":        2,
		"space-4":        1,
		"type-body":      1,
		"type-caption":   1,
		"type-display":   1,
		"type-heading":   1,
		"type-title":     1,
	}
}
func States() []State {
	c := Colors()
	return []State{
		{Name: "running", Label: "Running", Glyph: "", Color: c["running"]},
		{Name: "ready", Label: "Ready", Glyph: "●", Color: c["ready"]},
		{Name: "lost", Label: "Lost", Glyph: "◌", Color: c["lost"]},
		{Name: "dead", Label: "Dead", Glyph: "○", Color: c["dead"]},
		{Name: "archived", Label: "Archived", Glyph: "▧", Color: c["archived"]},
		{Name: "limit-reached", Label: "Limit reached", Glyph: "◆", Color: c["limit-reached"]},
	}
}

// Styles prescribes component treatments. Only Light/Dark/System will be user choices;
// these internal roles are not a palette customization API. Not installed until P5.
func Styles() map[string]lipgloss.Style {
	c, m := Colors(), Metrics()
	border := func(rounded int) lipgloss.Border {
		if rounded == 1 {
			return lipgloss.RoundedBorder()
		}
		return lipgloss.NormalBorder()
	}
	body := lipgloss.NewStyle().Foreground(c["ink"]).Background(c["surface"])
	return map[string]lipgloss.Style{
		"body":     body,
		"muted":    body.Foreground(c["ink-muted"]),
		"title":    body.Bold(true),
		"selected": body.Background(c["surface-raised"]).Bold(true),
		"focus":    body.Border(lipgloss.NormalBorder()).BorderForeground(c["accent"]),
		"dialog":   body.Background(c["surface-raised"]).Border(border(m["radius-dialog"])).BorderForeground(c["border"]).Padding(0, m["space-3"]),
		"error":    body.Foreground(c["dead"]),
	}
}
