// Code generated by scripts/gen-design; DO NOT EDIT.
// Package theme provides the fixed semantic TUI design roles.
// TUI colours follow tokens within termenv's rounding; the web is exact.
package theme

import "github.com/charmbracelet/lipgloss"

type State struct {
	Name, Label, Glyph string
	Color              lipgloss.AdaptiveColor
}

// Colors returns fresh semantic light/dark pairs; terminal capability resolution belongs to lipgloss.
func Colors() map[string]lipgloss.AdaptiveColor {
	return map[string]lipgloss.AdaptiveColor{
		"accent":         {Light: "#2d6271", Dark: "#2296f3"},
		"archived":       {Light: "#4c566a", Dark: "#d8dee9"},
		"border":         {Light: "#657084", Dark: "#3d3d3d"},
		"dead":           {Light: "#883b43", Dark: "#e4c8cd"},
		"ink":            {Light: "#2e3440", Dark: "#cccccc"},
		"ink-muted":      {Light: "#4c566a", Dark: "#9d9d9d"},
		"limit-reached":  {Light: "#73436b", Dark: "#dbb9d5"},
		"lost":           {Light: "#705014", Dark: "#ebcb8b"},
		"ready":          {Light: "#405430", Dark: "#d5e2cc"},
		"running":        {Light: "#4c566a", Dark: "#d8dee9"},
		"surface":        {Light: "#f8f9fc", Dark: "#1f1f1f"},
		"surface-raised": {Light: "#eceff4", Dark: "#2b2b2b"},
	}
}

type Palette struct {
	Accent        lipgloss.AdaptiveColor
	Archived      lipgloss.AdaptiveColor
	Border        lipgloss.AdaptiveColor
	Dead          lipgloss.AdaptiveColor
	Ink           lipgloss.AdaptiveColor
	InkMuted      lipgloss.AdaptiveColor
	LimitReached  lipgloss.AdaptiveColor
	Lost          lipgloss.AdaptiveColor
	Ready         lipgloss.AdaptiveColor
	Running       lipgloss.AdaptiveColor
	Surface       lipgloss.AdaptiveColor
	SurfaceRaised lipgloss.AdaptiveColor
}

// Roles returns the fixed palette with compile-time role names.
func Roles() Palette {
	c := Colors()
	return Palette{
		Accent:        c["accent"],
		Archived:      c["archived"],
		Border:        c["border"],
		Dead:          c["dead"],
		Ink:           c["ink"],
		InkMuted:      c["ink-muted"],
		LimitReached:  c["limit-reached"],
		Lost:          c["lost"],
		Ready:         c["ready"],
		Running:       c["running"],
		Surface:       c["surface"],
		SurfaceRaised: c["surface-raised"],
	}
}

// Metrics are terminal cells, rows or flags as documented in design/tokens.json.
func Metrics() map[string]int {
	return map[string]int{
		"radius-control": 0,
		"radius-dialog":  1,
		"space-1":        1,
		"space-2":        1,
		"space-3":        2,
		"space-4":        1,
		"type-body":      1,
		"type-caption":   1,
		"type-display":   1,
		"type-heading":   1,
		"type-title":     1,
	}
}
func States() []State {
	c := Colors()
	return []State{
		{Name: "running", Label: "Running", Glyph: "", Color: c["running"]},
		{Name: "ready", Label: "Ready", Glyph: "●", Color: c["ready"]},
		{Name: "lost", Label: "Lost", Glyph: "◌", Color: c["lost"]},
		{Name: "dead", Label: "Dead", Glyph: "○", Color: c["dead"]},
		{Name: "archived", Label: "Archived", Glyph: "▧", Color: c["archived"]},
		{Name: "limit-reached", Label: "Limit reached", Glyph: "◆", Color: c["limit-reached"]},
	}
}

// Styles prescribes component treatments. Only Light/Dark/System will be user choices;
// these internal roles are not a palette customization API.
type StyleSet struct{ Body, Muted, Title, Selected, Pane, PaneHeader, Focus, Dialog, Error lipgloss.Style }

func Styles() StyleSet {
	c, m := Colors(), Metrics()
	border := func(rounded int) lipgloss.Border {
		if rounded == 1 {
			return lipgloss.RoundedBorder()
		}
		return lipgloss.NormalBorder()
	}
	body := lipgloss.NewStyle().Foreground(c["ink"]).Background(c["surface"])
	return StyleSet{
		Body:       body,
		Muted:      body.Foreground(c["ink-muted"]),
		Title:      body.Bold(true),
		Selected:   body.Background(c["surface-raised"]).Bold(true),
		Pane:       body.Border(lipgloss.NormalBorder()).BorderForeground(c["border"]),
		PaneHeader: body.Background(c["surface-raised"]).Bold(true),
		Focus:      body.Border(lipgloss.NormalBorder()).BorderForeground(c["accent"]),
		Dialog:     body.Background(c["surface-raised"]).Border(border(m["radius-dialog"])).BorderForeground(c["border"]).Padding(0, m["space-3"]),
		Error:      body.Foreground(c["dead"]),
	}
}
