// Package designtokens generates the staged interface contract without loading af
// configuration, starting the app, or contacting a daemon.
package designtokens

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type Color struct{ Light, Dark, Role string }
type Value struct {
	CSS  string
	TUI  int
	Role string
}
type State struct{ Name, Label, Glyph, Color string }
type Tokens struct {
	Colors map[string]Color
	Values map[string]Value
	States []State
}

func keys[T any](m map[string]T) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// Generate returns all artifacts in memory, so checking drift never rewrites files.
func Generate(root string) (map[string][]byte, error) {
	raw, err := os.ReadFile(filepath.Join(root, "design/tokens.json"))
	if err != nil {
		return nil, err
	}
	var t Tokens
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	if err = dec.Decode(&t); err != nil {
		return nil, err
	}
	if err = validate(t); err != nil {
		return nil, err
	}
	css := cssTokens(t)
	goFile, err := goTokens(t)
	if err != nil {
		return nil, err
	}
	guide, err := guidePage(root, t)
	if err != nil {
		return nil, err
	}
	return map[string][]byte{
		"web/src/tokens.css":          css,
		"ui/theme/theme.go":           goFile,
		"docs/stylesheets/tokens.css": css,
		"docs/design/style-guide.md":  guide,
	}, nil
}

func cssTokens(t Tokens) []byte {
	var b strings.Builder
	b.WriteString("/* Code generated by scripts/gen-design; DO NOT EDIT. */\n")
	// Explicit scoped selectors make both themes visible together, without changing
	// any live web defaults or the surrounding MkDocs theme.
	for _, mode := range []string{"light", "dark"} {
		fmt.Fprintf(&b, "[data-af-theme=%q] {\n  color-scheme: %s;\n", mode, mode)
		for _, k := range keys(t.Colors) {
			c := t.Colors[k]
			v := c.Light
			if mode == "dark" {
				v = c.Dark
			}
			fmt.Fprintf(&b, "  --af-%s: %s;\n", k, v)
		}
		for _, k := range keys(t.Values) {
			fmt.Fprintf(&b, "  --af-%s: %s;\n", k, t.Values[k].CSS)
		}
		for _, s := range t.States {
			fmt.Fprintf(&b, "  --af-glyph-%s: %s;\n", s.Name, strconv.Quote(s.Glyph))
		}
		b.WriteString("}\n")
	}
	return []byte(b.String())
}

func goTokens(t Tokens) ([]byte, error) {
	var b strings.Builder
	b.WriteString(`// Code generated by scripts/gen-design; DO NOT EDIT.
// Package theme is the staged P0 palette. Live ui.Theme remains unchanged until P5.
package theme
import "github.com/charmbracelet/lipgloss"
type State struct { Name, Label, Glyph string; Color lipgloss.AdaptiveColor }
// Colors returns fresh semantic light/dark pairs; terminal capability resolution belongs to lipgloss.
func Colors() map[string]lipgloss.AdaptiveColor { return map[string]lipgloss.AdaptiveColor{
`)
	for _, k := range keys(t.Colors) {
		c := t.Colors[k]
		fmt.Fprintf(&b, "%q: {Light: %q, Dark: %q},\n", k, c.Light, c.Dark)
	}
	b.WriteString("} }\n// Metrics are terminal cells, rows or flags as documented in design/tokens.json.\nfunc Metrics() map[string]int { return map[string]int{\n")
	for _, k := range keys(t.Values) {
		fmt.Fprintf(&b, "%q: %d,\n", k, t.Values[k].TUI)
	}
	b.WriteString("} }\nfunc States() []State { c := Colors(); return []State{\n")
	for _, s := range t.States {
		fmt.Fprintf(&b, "{Name: %q, Label: %q, Glyph: %q, Color: c[%q]},\n", s.Name, s.Label, s.Glyph, s.Color)
	}
	b.WriteString(`} }
// Styles is a fresh lipgloss component foundation, deliberately not installed globally.
func Styles() map[string]lipgloss.Style {
 c, m := Colors(), Metrics()
 border := func(rounded int) lipgloss.Border { if rounded == 1 { return lipgloss.RoundedBorder() }; return lipgloss.NormalBorder() }
 body := lipgloss.NewStyle().Foreground(c["ink"]).Background(c["canvas"])
 return map[string]lipgloss.Style{
 "body": body,
 "muted": body.Foreground(c["muted"]),
 "title": body.Bold(m["weight-strong"] == 1),
 "selected": body.Background(c["selection"]).Bold(m["weight-strong"] == 1),
 "focus": body.Border(border(m["radius-none"])).BorderForeground(c["focus"]),
 "dialog": body.Background(c["raised"]).Border(border(m["radius-dialog"])).BorderForeground(c["border"]).Padding(m["space-0"], m["space-4"]),
 "error": body.Foreground(c["danger"]),
 }
}
`)
	return format.Source([]byte(b.String()))
}

// Write updates only declared outputs; it never invokes the application.
func Write(root string, outputs map[string][]byte) error {
	for _, p := range keys(outputs) {
		full := filepath.Join(root, p)
		if err := os.MkdirAll(filepath.Dir(full), 0755); err != nil {
			return err
		}
		if err := os.WriteFile(full, outputs[p], 0644); err != nil {
			return err
		}
	}
	return nil
}

// Check detects changed, missing and uncommitted-output content without mutation.
func Check(root string, outputs map[string][]byte) error {
	for _, p := range keys(outputs) {
		got, err := os.ReadFile(filepath.Join(root, p))
		if err != nil || !bytes.Equal(got, outputs[p]) {
			return fmt.Errorf("stale generated file %s; run make docs", p)
		}
	}
	return nil
}
