#!/usr/bin/env bash
#
# Regenerate the autogenerated docs reference pages (CLI + HTTP API) from the
# code, so they can never drift. Writes docs/reference/cli.md and
# docs/reference/api.md via the hidden `af gen-docs` command, which walks the
# live Cobra command tree and the daemon's HTTP route catalog.
#
# CI runs this and fails if the committed output differs (see
# .github/workflows/docs.yml), so run it and commit the result whenever you add
# or change a command, flag, or HTTP route.
set -euo pipefail

cd "$(dirname "$0")/.."

out="docs/reference"
go run . gen-docs "$out"
